'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Courses',
      [
        {
          course_name: 'Desenvolvimento de Sistemas',
          course_desc: 'A área de Tecnologia da Informação se coloca entre as mais promissoras do mercado de trabalho. O técnico em Desenvolvimento de Sistemas é o profissional que analisa e projeta sistemas. Constrói, documenta, realiza testes e mantém sistemas de informação. Utiliza ambientes de desenvolvimento e linguagens de programação específica. Modela, implementa e mantém bancos de dados.',
          course_img: 'ds-red-card.png',
          course_workload: '240',
          course_curriculum: 'ds.pdf',
          course_period: 'Integral',
          course_vacancies: '40',
          course_coordinator: 'Elaine Cristina de Almeida Zanin',
          course_email: 'elaine.almeida23@etec.sp.gov.br',
          course_shift: 'Integral',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Química',
          course_desc: 'O técnico em Química é o profissional que atua no planejamento, na coordenação, na operação e controle dos processos industriais e equipamentos nos processos produtivos. Planeja e coordena os processos laboratoriais. Realiza amostragens, análises químicas, físico-químicas e microbiológicas. O profissional também pode atuar em Indústrias, empresas de comercialização e assistência técnica, laboratórios de ensino, de calibração, de análise e controle de qualidade e ambiental, entidades de certificação de produtos, tratamento de águas e de efluente.',
          course_img: 'quim-red-card.png',
          course_workload: '240',
          course_curriculum: 'quimica.pdf',
          course_period: 'Integral',
          course_vacancies: '40',
          course_coordinator: 'Paula Cassiano Zandoná de Oliveira',
          course_email: 'paula.oliveira132@etec.sp.gov.br',
          course_shift: 'Integral',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Eletrônica',
          course_desc: 'O técnico em Eletrônica é o profissional que realiza o desenvolvimento de projetos de sistemas eletrônicos embarcados aplicando tecnologia de circuitos microprocessados e microcontrolados, bem como semicondutores de potência e componentes microeletrônicos. Executa e supervisiona trabalhos de instalação e reparo de equipamentos, sistemas. Realiza testes de calibração em equipamentos eletrônicos com o uso de aparelhos eletrônicos de medição. Aplica técnicas e métodos de controle de erros e defeitos na linha produção. Participa na identificação e atuação nas causas geradoras de defeito a fim de manter a qualidade dos produtos e serviços. Aplica em suas atividades as normas de segurança do trabalho e meio ambiente. Mantém o local de trabalho em conformidade com normas técnicas e padrões nacionais e internacionais',
          course_img: 'elet-red-card.png',
          course_workload: '240',
          course_curriculum: 'eletronica.pdf',
          course_period: 'Integral',
          course_vacancies: '40',
          course_coordinator: 'Roberta Maria Pavani Manzolli Bertoni',
          course_email: 'roberta.bertoni@etec.sp.gov.br',
          course_shift: 'Integral',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Eventos',
          course_desc: 'O curso Ensino Médio com Habilitação Profissional de Técnico em Eventos prepara o aluno para atuar no planejamento, organização e execução de diversos tipos de eventos, utilizando normas de cerimonial e protocolo, além dos procedimentos técnicos de recepção e acolhimento aos participantes. Desenvolve competências para atuar na logística de eventos, orientar a montagem e ambientação dos espaços, preparar e aplicar atividades de recreação e acompanhar a organização e o serviço de gastronomia em eventos.',
          course_img: 'even-red-card.png',
          course_workload: '240',
          course_curriculum: 'pdf.pdf',
          course_period: 'Integral',
          course_vacancies: '40',
          course_coordinator: 'Ana Carolina Angeli',
          course_email: 'ana.angeli3@etec.sp.gov.br',
          course_shift: 'Vespertino',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Linguagens, Ciências Humanas e Sociais',
          course_desc: 'Ao optar por essa modalidade, o aluno tem a oportunidade de se aprofundar em linguagem oral e escrita, exercitar capacidades intelectuais e expressivas, aprender a língua materna e idiomas estrangeiros, bem como estudar o homem do ponto de vista social, cultural e histórico. Ao concluir o Ensino Médio com ênfase em Linguagens, Ciências Humanas e Sociais o estudante poderá prosseguir estudos em nível superior preferencialmente nas áreas de: Administração, Direito, Letras, Marketing, Moda, Psicologia, Publicidade, Hospitalidade, entre outras.',
          course_img: 'ling-red-card.png',
          course_workload: '240',
          course_curriculum: 'pdf.pdf',
          course_period: 'Integral',
          course_vacancies: '40',
          course_coordinator: 'Lidiane Farchi de Paula',
          course_email: 'lidiane.paula2@etec.sp.gov.br',
          course_shift: 'Vespertino',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Ciências Biológicas',
          course_desc: 'As aulas do Ensino Médio com ênfase em Ciências Biológicas, Agrárias e da Saúde são realizadas no período da manhã. O estudante que optar por esta modalidade vai estudar os efeitos das atividades humanas sobre os ecossistemas, analisar o meio ambiente e seus fatores físicos, químicos, biológicos, econômicos, sociais e culturais e poderá ser capaz de argumentar com base em fatos e fontes diversas, cuidar de sua saúde física e emocional e agir com flexibilidade nos campos de atuação social.',
          course_img: 'cbas-red-card.png',
          course_workload: '240',
          course_curriculum: 'pdf.pdf',
          course_period: 'Integral',
          course_vacancies: '40',
          course_coordinator: 'Lidiane Farchi de Paula',
          course_email: 'lidiane.paula2@etec.sp.gov.br',
          course_shift: 'Vespertino',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Edificações',
          course_desc: 'O Técnico Em Edificações é o profissional que desenvolve e executa projetos de edificações, atendendo às legislações e normas técnicas específicas, normativas de segurança, de qualidade e ambientais nos limites de sua atribuição profissional. Planeja a execução de orçamentos de obra. Atua no planejamento, controle e gestão de obras. Realiza ensaios de materiais e de solo, e inspeções de rotina. Coordena e executa serviços de manutenção e de instalações em edificações.',
          course_img: 'edif-red-card.png',
          course_workload: '240',
          course_curriculum: 'pdf.pdf',
          course_period: 'Integral',
          course_vacancies: '40',
          course_coordinator: 'Claudia Lima Truzzi Perondini',
          course_email: 'claudia.perondini01@etec.sp.gov.br',
          course_shift: 'Matutino',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Contabilidade',
          course_desc: 'É o profissional que desempenha tarefas relativas à contabilidade e à administração das organizações. Analisa a documentação contábil e elabora planos de contas. Organiza, controla e arquiva documentos relativos à atividade contábil/administrativa e controla as movimentações. Constitui e regulariza empresas, identifica documentos e informações, atende à fiscalização e procede a consultoria empresarial. Executa a contabilidade geral, operacionaliza a contabilidade de custos e efetua contabilidade gerencial. Administra o departamento de pessoal e realiza controle patrimonial.',
          course_img: 'contabilidade-blue-card.png',
          course_workload: '240',
          course_curriculum: 'contabilidade.pdf',
          course_period: 'Parcial',
          course_vacancies: '40',
          course_coordinator: 'Coordenador',
          course_email: 'Coordenador@etec.sp.gov.br',
          course_shift: 'Noturno',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Eletrotécnica',
          course_desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis in eu mi bibendum neque egestas congue quisque. Vitae et leo duis ut diam quam nulla. Est sit amet facilisis magna etiam tempor. Justo nec ultrices dui sapien eget. Aliquet bibendum enim facilisis gravida neque. Consectetur adipiscing elit ut aliquam purus sit. Et tortor consequat id porta nibh venenatis cras sed felis. Eget sit amet tellus cras adipiscing enim eu turpis. Neque ornare aenean euismod elementum. Tempus egestas sed sed risus pretium quam vulputate dignissim. Nec tincidunt praesent semper feugiat. Elementum tempus egestas sed sed. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Placerat duis ultricies lacus sed turpis. Ornare arcu dui vivamus arcu felis. Nunc mi ipsum faucibus vitae. Mollis nunc sed id semper risus in.',
          course_img: 'eletrotecnica-blue-card.png',
          course_workload: '240',
          course_curriculum: 'pdf.pdf',
          course_period: 'Parcial',
          course_vacancies: '40',
          course_coordinator: 'Coordenador',
          course_email: 'Coordenador@etec.sp.gov.br',
          course_shift: 'Noturno',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Enfermagem',
          course_desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis in eu mi bibendum neque egestas congue quisque. Vitae et leo duis ut diam quam nulla. Est sit amet facilisis magna etiam tempor. Justo nec ultrices dui sapien eget. Aliquet bibendum enim facilisis gravida neque. Consectetur adipiscing elit ut aliquam purus sit. Et tortor consequat id porta nibh venenatis cras sed felis. Eget sit amet tellus cras adipiscing enim eu turpis. Neque ornare aenean euismod elementum. Tempus egestas sed sed risus pretium quam vulputate dignissim. Nec tincidunt praesent semper feugiat. Elementum tempus egestas sed sed. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Placerat duis ultricies lacus sed turpis. Ornare arcu dui vivamus arcu felis. Nunc mi ipsum faucibus vitae. Mollis nunc sed id semper risus in.',
          course_img: 'enfermagem-blue-card.png',
          course_workload: '240',
          course_curriculum: 'pdf.pdf',
          course_period: 'Parcial',
          course_vacancies: '40',
          course_coordinator: 'Coordenador',
          course_email: 'Coordenador@etec.sp.gov.br',
          course_shift: 'Noturno',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Informática',
          course_desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis in eu mi bibendum neque egestas congue quisque. Vitae et leo duis ut diam quam nulla. Est sit amet facilisis magna etiam tempor. Justo nec ultrices dui sapien eget. Aliquet bibendum enim facilisis gravida neque. Consectetur adipiscing elit ut aliquam purus sit. Et tortor consequat id porta nibh venenatis cras sed felis. Eget sit amet tellus cras adipiscing enim eu turpis. Neque ornare aenean euismod elementum. Tempus egestas sed sed risus pretium quam vulputate dignissim. Nec tincidunt praesent semper feugiat. Elementum tempus egestas sed sed. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Placerat duis ultricies lacus sed turpis. Ornare arcu dui vivamus arcu felis. Nunc mi ipsum faucibus vitae. Mollis nunc sed id semper risus in.',
          course_img: 'informatica-blue-card.png',
          course_workload: '240',
          course_curriculum: 'pdf.pdf',
          course_period: 'Parcial',
          course_vacancies: '40',
          course_coordinator: 'Coordenador',
          course_email: 'Coordenador@etec.sp.gov.br',
          course_shift: 'Noturno',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Mecânica',
          course_desc: 'O técnico em Mecânica é o profissional que elabora projetos mecânicos e sistemas automatizados. Monta e instala máquinas e equipamentos. Planeja e realiza manutenção. Desenvolve processos de fabricação e montagem de conjuntos mecânicos. Elabora documentação, realiza compras e vendas técnicas e cumpre normas e procedimentos de segurança no trabalho e preservação ambiental.',
          course_img: 'mecanica-blue-card.png',
          course_workload: '240',
          course_curriculum: 'mecanica.pdf',
          course_period: 'Parcial',
          course_vacancies: '40',
          course_coordinator: 'Coordenador',
          course_email: 'Coordenador@etec.sp.gov.br',
          course_shift: 'Noturno',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          course_name: 'Turismo Receptivo',
          course_desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis in eu mi bibendum neque egestas congue quisque. Vitae et leo duis ut diam quam nulla. Est sit amet facilisis magna etiam tempor. Justo nec ultrices dui sapien eget. Aliquet bibendum enim facilisis gravida neque. Consectetur adipiscing elit ut aliquam purus sit. Et tortor consequat id porta nibh venenatis cras sed felis. Eget sit amet tellus cras adipiscing enim eu turpis. Neque ornare aenean euismod elementum. Tempus egestas sed sed risus pretium quam vulputate dignissim. Nec tincidunt praesent semper feugiat. Elementum tempus egestas sed sed. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Placerat duis ultricies lacus sed turpis. Ornare arcu dui vivamus arcu felis. Nunc mi ipsum faucibus vitae. Mollis nunc sed id semper risus in.',
          course_img: 'turismo-blue-card.png',
          course_workload: '240',
          course_curriculum: 'pdf.pdf',
          course_period: 'Parcial',
          course_vacancies: '40',
          course_coordinator: 'Coordenador',
          course_email: 'Coordenador@etec.sp.gov.br',
          course_shift: 'Noturno',
          createdAt: new Date(),
          updatedAt: new Date(),
        }
      ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Courses', null, {});
  }
};
